package GUI;

import javax.swing.JOptionPane;
import java.util.Arrays;
import javax.swing.JOptionPane;

import civitas.CivitasJuego;
import civitas.GestorEstados;
import civitas.SalidasCarcel;
import civitas.Respuestas;
import GUI.GestionarDialog;
import civitas.Jugador;
import civitas.OperacionesJuego;
import java.util.ArrayList;

public class CivitasView extends javax.swing.JFrame {

    CivitasJuego juego;
    JugadorPanel jugadorPanel;
    CasillaPanel casillaPanel;
    GestionarDialog gestionarD;

    int gestionElegida;     // not sure
    int propiedadElegida;   // not sure

    public void setCivitasJuego(CivitasJuego j) {
        juego = j;
        setVisible(true);
    }

    public CivitasView() {
        initComponents();
        setLocationRelativeTo(null);

        jugadorPanel = new JugadorPanel();
        casillaPanel = new CasillaPanel();
        
        gestionarD = new GestionarDialog(this, rootPaneCheckingEnabled);
        
        contenedorVistaJugador.add(jugadorPanel);
        contenedorVistaCasilla.add(casillaPanel);

        repaint();
        revalidate();
    }

    void actualizarVista() {
        jugadorPanel.setJugador(juego.getJugadorActual());
        casillaPanel.setCasilla(juego.getCasillaActual());
        label_ranking.setVisible(false);
        ranking.setVisible(false);
        
        // Sin casillaPanel;
        //casillaActual.setText(juego.getCasillaActual().getNombre());

        if (juego.finalDelJuego()) {                              // Si es el final del juego
            
            ArrayList<Jugador> rank = new ArrayList(juego.ranking());

                for (int i = 0; i < rank.size(); i++) 
                    ranking.append( i+1 + ". " + rank.get(i).toString() + "\n");
            
            // Tambien vale pero no pondriamos el puesto de cada jugador
            //ranking.setText( String.valueOf(juego.ranking()) );
                
            label_ranking.setVisible(true);
            ranking.setVisible(true);

            repaint();
            revalidate();
        }
    }
    
    SalidasCarcel salirCarcel() {
        String[] opciones= {"Pagando", "Tirando"};
        
        int respuesta= JOptionPane.showOptionDialog(null, "¿Cómo quieres salir de la cárcel?",
                       "Salir de la cárcel", JOptionPane.DEFAULT_OPTION,
                       JOptionPane.QUESTION_MESSAGE,null, opciones, opciones[0] );
        
        SalidasCarcel salida;
        
        if (respuesta == 0)
            salida = SalidasCarcel.PAGANDO;
        else salida = SalidasCarcel.TIRANDO;
        
        return salida;
    }

    void mostrarSiguienteOperacion(OperacionesJuego op) {
        siguienteop.setText(String.valueOf(op));
        actualizarVista();
    }

    void mostrarEventos() {
        DiarioDialog diarioD= new DiarioDialog(this, true); //crea la ventana del diario
        //diarioD.repaint();
        //diarioD.revalidate();
    }

    Respuestas comprar() {
        int opcion = JOptionPane.showConfirmDialog(null, "¿Comprar la calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
        Respuestas res;

        if (opcion == 0) 
            res = Respuestas.SI;
        else 
            res = Respuestas.NO;

        return res;
    }

    public int getGestionElegida() {
        return gestionarD.getGestionElegida();
    }

    public int getPropiedadElegida() {
        return gestionarD.getPropiedadElegida();
    }
    
    public void gestionar() {
        gestionarD.gestionar(juego.getJugadorActual());
        gestionarD.pack();
        gestionarD.repaint();
        gestionarD.revalidate();
        
        gestionarD.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        contenedorVistaJugador = new javax.swing.JPanel();
        label_siguienteop = new javax.swing.JLabel();
        siguienteop = new javax.swing.JTextField();
        label_ranking = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ranking = new javax.swing.JTextArea();
        que_es_esto = new javax.swing.JLabel();
        contenedorVistaCasilla = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_siguienteop.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label_siguienteop.setText("Siguiente operación:");

        siguienteop.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        siguienteop.setText("Siguiente operación");
        siguienteop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteopActionPerformed(evt);
            }
        });

        label_ranking.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        label_ranking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ranking.setText("Ranking");

        ranking.setColumns(20);
        ranking.setRows(5);
        jScrollPane1.setViewportView(ranking);

        que_es_esto.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        que_es_esto.setText("CivitasView");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, que_es_esto, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), que_es_esto, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedorVistaCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label_siguienteop)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(siguienteop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_ranking, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(436, 436, 436)
                                .addComponent(que_es_esto)))
                        .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(que_es_esto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorVistaCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_siguienteop)
                    .addComponent(siguienteop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_ranking))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siguienteopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorVistaCasilla;
    private javax.swing.JPanel contenedorVistaJugador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_ranking;
    private javax.swing.JLabel label_siguienteop;
    private javax.swing.JLabel que_es_esto;
    private javax.swing.JTextArea ranking;
    private javax.swing.JTextField siguienteop;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
